### ISSUE TITLE
Spline interpolation error with NGC 2023 spectrum

### ISSUE THREAD

**Issue by karllark** [PAHFIT/pahfit#97]
When @Ameek-Sidhu was attempting to fit a Spitzer NGC 2023 spectrum, the code errored out with a spline interpolation error.  This is an error with the scipy spline code.

```
(base) [kgordon@grimy pahfit]$ ./scripts/run_pahfit spectrum_NGC_2023_south.ipac scipack_ExGal_SpitzerIRSSLLL.ipac
Traceback (most recent call last):
  File "./scripts/run_pahfit", line 90, in <module>
    pmodel = PAHFITBase(obs_x, obs_y, filename=packfile)
  File "/home/kgordon/Python_git/pahfit/pahfit/base.py", line 130, in __init__
    param_info = self.guess(obs_x, obs_y, param_info)
  File "/home/kgordon/Python_git/pahfit/pahfit/base.py", line 591, in guess
    sp = interpolate.splrep(obs_x, obs_y)
  File "/home/kgordon/Bin/miniconda3/lib/python3.8/site-packages/scipy/interpolate/fitpack.py", line 291, in splrep
    res = _impl.splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
  File "/home/kgordon/Bin/miniconda3/lib/python3.8/site-packages/scipy/interpolate/_fitpack_impl.py", line 512, in splrep
    raise _iermess[ier][1](_iermess[ier][0])
ValueError: Error on input data
```

**Comment by karllark** [comment]
NGC2023 spectrum.

```
|wavelength|              flux|             sigma|
|    double|            double|            double|
|    micron|                Jy|                Jy|
|      null|              null|              null|
   5.242817   778576299.764961  30460183.28290332 
   5.273802  755324894.2136203 30654436.510516923 
   5.304788  575004215.2833757 26988563.184604682 
   5.335773 526777364.70690465 26183742.761992607 
   5.366758  493510023.9469152  23184987.62148272 
   5.397744  489232308.1327962 25412772.293140933 
   5.428729  573062206.4626598  41513115.26955275 
   5.459714   593729290.364804 25419654.064182803 
     5.4907  565318313.5357717 17895668.411826905 
   5.521685  645132460.6846734 18545875.108958825 
    5.55267  681720929.4476918 19096037.263420608 
   5.583656  741372688.3593526 18168701.014831193 
   5.614641  907662586.9551525 18733050.056751553 
   5.645627 1152434731.6075833 19648159.367700852 
   5.676612  1289048788.895224 21780074.894454222 
   5.707598 1358445251.3877826 20164787.054065235 
   5.738583 1340072058.3128204 21151850.789261404 
   5.769568 1262205792.1396332  22497366.54563017 
   5.800553 1206148090.2785559  22824511.17374277 
   5.831539 1169698592.0273337  23616946.84996703 
   5.862525 1294328773.7574146  25225700.61845365 
    5.89351  1352524215.292913 27447957.581399407 
   5.924495 1373484436.7134933  28083047.92720223 
   5.955481  1440573968.065924  30142435.79234338 
   5.986466  1636362052.343256 31173832.349009544 
   6.017451  1980136814.832089  32882046.47949359 
   6.048437 2243484753.3757477    36153775.175763 
   6.079422 2508500154.5561457 31895764.158707455 
   6.110407 2899488511.2208705 36430425.619807065 
   6.141393 4079893463.9614854  36626352.77332585 
   6.172378   6173485543.13058  37722922.24191692 
   6.203363  8260910024.509442  43706565.03317732 
   6.234349  8775755250.555597  43715413.28322814 
   6.265334  7723949712.248189   40336503.1250204 
   6.296319  6355185800.005244 37634317.764702424 
   6.327305  5182443688.395952  36421885.12432214 
    6.35829  4361454395.851726 35658203.095364735 
   6.389276  3750431712.256419 32488712.411661126 
   6.420261  3322304911.343643 31143263.624843996 
   6.451246 2923082325.3411384     30307466.09963 
   6.482232   2736016662.09963 31339209.046005517 
   6.513217  2580829093.262242 33070950.909945626 
   6.544202  2402690481.895168  34425274.09295656 
   6.575188  2328616503.879763  36348541.52087503 
   6.606173  2412384859.272734  43202765.22321765 
   6.637158  2629107657.797416  45147692.64168111 
   6.668144 2615183126.7673597 47134631.555999406 
   6.699129 2660264440.5379357  42399570.10689123 
   6.730114  2614114623.939836   39350447.7403908 
     6.7611 2596420490.5382743  38271527.95377976 
   6.792085  2677533622.598144 38134301.693921216 
   6.823071 2685782394.6947794  39872482.73068845 
   6.854056  2728777304.270909  40805699.15122703 
   6.885041 2931626310.8547573  38259799.51597471 
   6.916027 3095201427.3266864 37602022.232884146 
   6.947012   3030705759.87532 36841954.879268415 
   6.977998  3112437073.876741 37742212.639477156 
   7.008983 3312721600.2726116 40783421.835257694 
   7.039968   3445429229.38981  40222717.43385061 
   7.070954 3485760107.4003396 40081282.454406686 
   7.101939  3559561901.856613 39955581.595855735 
   7.132924 3666827731.3270226  44004293.23271681 
    7.16391  3986164511.539236  48627969.88509541 
   7.194895  4043406920.669977   42949208.7228051 
   7.225881  4323808927.721059 47727381.028235964 
   7.256866   4665161609.78046  52832617.83624017 
   7.287851  5043551900.176403 57488033.290702485 
   7.318837  5374892282.716851  61661622.42238762 
   7.349822  5845043436.088452  67309957.98721306 
   7.380807  6554318282.993577  72154973.97645195 
   7.411793  7078193782.388656  71553705.73695263 
   7.442778  7641320967.809604  77745841.59584801 
   7.473763  8795540559.277538  74710395.86883068 
   7.504749  9058283344.723537  74465997.76292315 
   7.535734   9893253137.27509  81547449.64299469 
   7.533706  9904280605.059793  25736657.35049235 
   7.595799  11575003124.84394 25794097.787821535 
   7.657894 11622363439.436718 24578994.163038626 
   7.719988 10841974298.554502 21953226.464020036 
   7.782082 10376509112.454039 20522122.986970704 
   7.844176  9963893782.943396 19041471.421659313 
   7.906271  9036489265.583431  18132397.85711586 
   7.968365  7754185445.857013 16711871.144158788 
   8.030458  6677551730.120943 15101602.424744125 
   8.092554  5817843127.163555 14578173.643406058 
   8.154648  5375179319.115612 14297053.443245225 
   8.216742  5284903974.505749 14040935.636417422 
   8.278836  5385964354.540034 14274628.275870062 
    8.34093  5511318867.681071 14259250.463900711 
   8.403025  5740239039.104407   14482492.2782459 
   8.465118  6294443383.929483 15459698.032528378 
   8.527213  6980368070.417698  16285484.96450418 
   8.589307  7328550070.913993  17243231.70749065 
   8.651402  6952107158.867291 16628981.985089423 
   8.713495  5852829489.857052 15138227.631824087 
    8.77559  4696594922.445022 13665763.547657454 
   8.837685  3776404908.478074 12342731.570213566 
   8.899778  3106185644.602116 11215972.782502422 
   8.961872  2676683727.272531 10325838.787555706 
   9.023967  2377335861.347881  9582581.830830244 
   9.086061  2205747071.386178  8955581.889384005 
   9.148155 2103100219.6589198   8905574.14423495 
   9.210249  2060606794.674004   9149187.39536414 
   9.272344 2029643200.7229283  8208716.336077498 
   9.334438 1965071573.7531765  8018571.558792682 
   9.396532 1936494997.7187524  8282134.124413807 
   9.458626 1918685912.2034917  7715412.289520695 
    9.52072 1949962054.7401006  7492494.553864271 
   9.582815 2071696564.9693248  7516916.918243867 
   9.644909   2438730757.91663  7959232.233866036 
   9.707003  2411366218.452233  8177959.634033179 
   9.769097 2043812437.4499333   8258306.35560548 
   9.831192  1873735049.996383  8200730.828046233 
   9.893286 1823932014.8096006  7779328.633708108 
    9.95538 1789334995.6148233  7779896.988525288 
   10.01747 1797131405.0323524  8263350.708775351 
   10.07957  1809118506.151684   8418823.67646098 
   10.14166 1754534292.5335624  8461737.278825149 
   10.20376 1722879208.8054435  8621887.445687482 
   10.26585 1725634717.6694865  8216856.687539043 
   10.32795 1718314848.9710987   8562869.24343525 
   10.39004 1746758160.4245687  9386110.183033928 
   10.45213 1869014176.1847656   9073076.19130069 
   10.51423  2000619900.720937  8949931.112992106 
   10.57632 2198284590.4114075   7967848.78415252 
   10.63842  2360786845.176079  8300017.555393923 
   10.70051 2492031940.4163895  8340246.747720968 
    10.7626  2647925949.757539 7943977.7758818045 
    10.8247  2805195652.244037  8179086.066012001 
   10.88679  3154385238.433472  8526278.376092916 
   10.94889  3862760644.553492  9115600.450259222 
   11.01098  4704740072.807291 10326273.287412565 
   11.07308  5356084326.268012 10927773.444423882 
   11.13517  7466793378.256235 12858479.311208988 
   11.19726 11593609736.558187  15939485.59721061 
   11.25936 13654346679.914612 17857798.929695897 
   11.32145 11795181331.504707 17389835.353833873 
   11.38355  8961852855.106054 15849312.736903572 
   11.44564  6878746732.784034 14757084.223213052 
   11.50774  5595375933.545847 13998281.488452187 
   11.56983  4841515648.156937 13482457.039127998 
   11.63192  4336731754.122777 12808385.496373486 
   11.69402 4002736870.8170443 12614495.656231843 
   11.75611 3882938819.5849376 12637040.158720141 
   11.81821 3887734427.0230637  11952692.91101635 
    11.8803  4062631342.427644 12137406.202172488 
    11.9424 4224086847.0521717 11843860.479270143 
   12.00449 4262485550.0083303 11615878.667374678 
   12.06658 4169473391.9252687 11390019.494193645 
   12.12868 4048948713.1687045 11253838.725577293 
   12.19077  4011613442.393752 10694378.585209599 
   12.25287  4412844045.865695 11848092.983258806 
   12.31496   4666681050.72186 11309921.054876562 
   12.37705  4562347443.307617 11056326.363145385 
   12.43915  4747187430.431674  11210992.23622163 
   12.50124  5147876826.306904 11645440.071254501 
   12.56334  5609103527.616642 12375989.630339865 
   12.62543  6047929123.985684 12982796.598033538 
   12.68753  6439488937.328003 13502349.807712834 
   12.74962  6663513313.193007 14268023.157357892 
   12.81171 6269332406.0531845 14297278.696127879 
   12.87381  5168339363.026895 14049708.236041132 
    12.9359  4086191561.601175 13315069.082902608 
     12.998 3556485848.6966476  13221941.27543563 
   13.06009   3356386156.25299  12776647.23508729 
   13.12218  3286057882.881505 13043595.433067853 
   13.18428  3237396800.517495 13286781.120403951 
   13.24637  3253957944.724911  14190207.38129928 
   13.30847 3193043855.2593627 13186095.956639934 
   13.37056 3173504343.5415745 13349074.559547562 
   13.43266 3239293615.6986217 13550359.399374137 
   13.49475 3346889233.2583003 12764670.045762299 
   13.55684 3359334850.8225145 11781906.828543289 
   13.61894 3293864311.1110487 11468577.792570308 
   13.68103   3117889342.77089 11164292.419827787 
   13.74313  2918576630.408321 10960788.187315619 
   13.80522  2800624581.243736 10913816.757506244 
   13.86732 2774590194.8700275  10566905.55319213 
   13.92941 2788491464.3281465 11099569.102288285 
    13.9915  2850559586.715173 11495718.179116165 
    14.0536  2862021107.667059 11707680.975010589 
   14.11569 2913041452.4828362 13500924.971859202 
   14.17779  3012592539.232544  13536668.85489873 
   14.23988 3046293713.6471963  13927660.96824321 
   14.30198 2953291238.8178754 15852464.661797605 
   14.36407  2845889286.332665  14204958.24229129 
   14.42616  2748433042.096404 13964159.400135243 
   14.48826  2696130481.089552 14453107.235429104 
   14.55035 2651569537.6239686 14930593.749012042 
   14.61245   2582315386.36229 14922402.316858362 
   14.67454 2486732707.9108367 13662717.041753583 
   14.73664 2388504487.8430796 13058258.674009936 

```
